services:
    outline-admin:
        image: amro045/outline-admin:latest
        container_name: outline-admin
        ports:
            - "3025:3025"
        volumes:
            - "./oa_data:/app/data"
        networks:
            - outline_admin
        restart: unless-stopped

networks:
    outline_admin:
        driver: bridge
